version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/family_tree.db
    command: >
      sh -c "chmod 777 /app && npm start"